
datadump.location:
    author: C:\Users\gurki\Downloads\test-authors.txt
    works: C:\Users\gurki\Downloads\test-works.txt
spring:
  application:
    name: betterreads
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 7ee0f42641b5de0b8a76
            client-secret: 2b6b0932dbe7e05ab84290cd90ce4598289b1df5
  data:
    cassandra:
      keyspace-name: main
      username: siZRBtPypZvZAQgGqbGwhBYN
      password: b._BaXKvzZbzZGrr-Rsm1Msqx-7sZYo1oRAZz+sfWyk9GqhAgfMbUrfsxQuXS1R0EExomuSq8UaId1SDOsPr8jDW6FcZjDYS6MhAg5zJRqJfuj.WAQ-H7XxvZLAzvZQE
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
        
datastax.astra:
    secure-connect-bundle: secure-connect-booksdata.zip

astra.db:
  id: d88e5cac-99df-495c-8375-0df71285f504
  region: us-east1
  keyspace: main
  application.token: AstraCS:siZRBtPypZvZAQgGqbGwhBYN:20293da484148b5d3ad19ca9167b9dc639b9d2cc90ce4e95a73565518be9c907